on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Yarn install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command
      - name: Create Release From Tag
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          echo "Tag: ${{ github.ref_name }}"
          echo "Event is: ${{ github.event.ref }}"
          ./create-release.sh ${{ github.ref_name }}
          ls -al
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: theme file
          path: |
            ${{ github.ref_name }}.zip
