on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup nodejs 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Yarn install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
      - name: Create Release From Tag
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          echo "Tag: ${{ github.ref_name }}"
          echo "Event is: ${{ github.event.ref }}"
          ./create-release.sh ${{ github.ref_name }}
          ls -al
          gh release upload ${{github.event.release.tag_name}} ${{ github.ref_name }}.zip



